name: testing_w
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  http: ^1.6.0
  shared_preferences: ^2.1.5
  sizer: ^3.1.3
  go_router: ^17.0.1
  google_fonts: ^6.3.3
  # url_strategy: ^0.4.3 # discontinued package
  percent_indicator: ^4.2.2
  syncfusion_flutter_charts: ^31.2.18
  syncfusion_flutter_core: ^31.2.18
  syncfusion_flutter_gauges: ^31.2.18
  syncfusion_flutter_datagrid: ^31.2.18
  intl: ^0.20.2
  flutter_svg: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - asset/image/
    - asset/icon/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
scripts:
  up: flutter pub upgrade && flutter pub upgrade --major-versions
